version: '3.8'

services:
  app:
    build: ./app
    container_name: app
    command: gunicorn --bind 0.0.0.0:5000 app:app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flask_dbname
    volumes:
      - ./app:/app
    expose:
      - 5000
    depends_on:
      - pgadmin

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_dbname

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@dev.ru
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=5555
  
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
      - pgadmin